# The object the client sends to create a new inventory entry
ProductSizeInput:
  type: object
  properties:
    productId:
      type: integer
      description: The numeric primary key ID of the product.
    sizeId:
      type: integer
      description: The numeric primary key ID of the size.
    quantity:
      type: integer
      description: The initial stock quantity for this combination.
      minimum: 0
  required:
    - productId
    - sizeId
    - quantity

# The object the client sends to update an inventory entry
UpdateProductSizeInput:
  type: object
  properties:
    quantity:
      type: integer
      description: The new stock quantity for this combination.
      minimum: 0
  required:
    - quantity

# The full inventory object returned by the API
ProductSizeView:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    quantity:
      type: integer
      description: The current available stock.
    sold:
      type: integer
      description: The total number of units sold.
      readOnly: true
    productData:
      $ref: './product.yaml#/ProductSummary'
    sizeData:
      $ref: './size.yaml#/Size'

# The shape of the response for the paginated GET endpoint
PaginatedProductSizes:
  type: object
  properties:
    totalItems:
      type: integer
    totalPages:
      type: integer
    currentPage:
      type: integer
    productSizes:
      type: array
      items:
        $ref: '#/ProductSizeView'