# /schemas/auth.yaml
# In docs/openapi.yaml

tags:
  # ... your other tags
  - name: Brands
    description: Operations related to product brands.

paths:
  # ... your other paths
  /brands:
    $ref: './paths/brands.yaml#/paths/~1brands'
  /brands/{id}:
    $ref: './paths/brands.yaml#/paths/~1brands~1{id}'

components:
  schemas:
    # ... your other schemas
    Brand:
      $ref: './schemas/brand.yaml#/Brand'
    BrandInput:
      $ref: './schemas/brand.yaml#/BrandInput'
    PaginatedBrands:
      $ref: './schemas/brand.yaml#/PaginatedBrands'

RegisterInput:
  type: object
  properties:
    email:
      type: string
      format: email
    password:
      type: string
      format: password
      minLength: 6
    userName:
      type: string
    roleId:
      type: integer
      description: The numeric ID of the role to assign (e.g., 2 for Customer).
  required: [email, password, userName, roleId]

LoginInput:
  type: object
  properties:
    email:
      type: string
      format: email
    password:
      type: string
  required: [email, password]

PasswordResetInput:
  type: object
  properties:
    email:
      type: string
      format: email
    otpCode:
      type: string
      example: '123456'
    password:
      type: string
      format: password
      minLength: 6
  required: [email, otpCode, password]

AuthTokensResponse:
  type: object
  properties:
    errCode:
      type: integer
    message:
      type: string
    data:
      type: object
      properties:
        access_token:
          type: string
          format: jwt
        refresh_token:
          type: string
          format: jwt