openapi: 3.0.0
info:
  title: BAMITO Badminton Shop API
  version: 1.0.0
  description: The official API documentation for the BAMITO e-commerce backend.

servers:
  - url: https://your-production-domain.com/api/v1
    description: Production Server
  - url: http://localhost:8080/api/v1
    description: Local Development Server

tags:
  - name: Authentication
  - name: Users
  # --- ADD THESE NEW TAGS ---
  - name: Products
    description: Publicly accessible endpoints for viewing products.
  - name: Products (Admin)
    description: Secure endpoints for managing the product catalog.
  # ---
  - name: Brands
  # ... and so on for all your other resources

paths:
  # ... your existing paths for auth, users, etc.
  
  # --- ADD THE NEW PRODUCT PATHS ---
  /products:
    $ref: './paths/products.yaml#/paths/~1products'
  /products/{productId}:
    $ref: './paths/products.yaml#/paths/~1products~1{productId}'
  /products/{productId}/feedback:
    $ref: './paths/products.yaml#/paths/~1products~1{productId}~1feedback'
  /products/sale-off:
    $ref: './paths/products.yaml#/paths/~1products~1sale-off'
  /products/types/{productTypeId}:
    $ref: './paths/products.yaml#/paths/~1products~1types~1{productTypeId}'
  /products/{id}:
    $ref: './paths/products.yaml#/paths/~1products~1{id}'
  # ---

  # ... your other paths for brands, etc.

components:
  securitySchemes:
    $ref: './components/security.yaml'
  schemas:
    # ... your existing schemas
    
    # --- ADD THE NEW PRODUCT SCHEMAS ---
    ProductInput:
      $ref: './schemas/product.yaml#/ProductInput'
    ProductSummary:
      $ref: './schemas/product.yaml#/ProductSummary'
    ProductDetail:
      $ref: './schemas/product.yaml#/ProductDetail'
    PaginatedProducts:
      $ref: './schemas/product.yaml#/PaginatedProducts'
    # ---

    # ... your other schemas for Brand, Error, etc.